project_id = "nkekijcefghncihokotz"

[functions.analyze-sentiment]
verify_jwt = true

[functions.ai-research-assistant]
verify_jwt = true

[functions.ai-news-summarizer]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true
